version: '2'

services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend


  liquibase-migrations:
    image: liquibase/liquibase:4.25
    container_name: liquibase-migrations
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend


  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181


  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "29091:29091"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9091,PLAINTEXT_HOST://host.docker.internal:29091
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9091,PLAINTEXT_HOST://0.0.0.0:29091
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      ZOOKEEPER: "zoo1:2181"

      #      When adding new brokers it makes sense to increase the value
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    depends_on:
      - zoo1
    volumes:
      - kafka1:/var/lib/kafka/data


  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    environment:
      TZ: Europe/Moscow
    ports:
      - "9090:9090"
    networks:
      - backend


  grafana:
    image: grafana/grafana-oss:10.4.2
    container_name: grafana
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - backend


  scrapper:
    build:
      context: /scrapper
      dockerfile: Dockerfile
    container_name: scrapper-app
    depends_on:
      postgresql:
        condition: service_started
      liquibase-migrations:
        condition: service_completed_successfully
      kafka1:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/scrapper
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:29091
      BOT_BASE_URL: http://bot-app:8090
    ports:
      - "8080:8080"
    networks:
      - backend


  bot:
    build:
      context: /bot
      dockerfile: Dockerfile
    container_name: bot-app
    depends_on:
      scrapper:
        condition: service_started
      kafka1:
        condition: service_started
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:29091
      SCRAPPER_BASE_URL: http://scrapper-app:8080

#      Your Telegram bot token
      TELEGRAM_TOKEN: ${YOUR_TELEGRAM_BOT_TOKEN}
    ports:
      - "8090:8090"
    networks:
      - backend


volumes:
  postgresql:
  kafka1:
  prometheus:
  grafana:

networks:
  backend:
