app:
  scheduler:
    enable: true
    interval: 300s
    link-check-interval: 300s
    force-check-delay: 10s
  database-access-type: jpa

datasource:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/scrapper
  username: postgres
  password: postgres

spring:
  jpa:
    openInView: false
    showSql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  application:
    name: scrapper
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

bot:
  base-url: http://localhost:8090

github:
  base-url: https://api.github.com

stackoverflow:
  base-url: https://api.stackexchange.com

springdoc:
  swagger-ui:
    path: /swagger-ui
