app:
  scheduler:
    enable: true
    interval: 10s
    link-check-interval: 10s
    force-check-delay: 10s
  database-access-type: jpa

datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

bot:
  base-url: http://localhost:8090

github:
  base-url: https://api.github.com

stackoverflow:
  base-url: https://api.stackexchange.com

springdoc:
  swagger-ui:
    path: /swagger-ui
