app:
  scheduler:
    enable: true
    interval: 300s
    link-check-interval: 300s
    force-check-delay: 10s

  database-access-type: jpa
  use-queue: true

  kafka:
    topic:
      name: "notifications"
      partitions: 2
      replicas: 1


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  application:
    name: scrapper

  liquibase:
    enabled: false

  kafka:
    bootstrap-servers: localhost:29091
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1


server:
  port: 8080


management:
  server.port: 8180
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure.include: info,health,prometheus
      path-mapping.prometheus: /metrics
  endpoint:
    info.enabled: true
    health.enabled: true
    prometheus.enabled: true
  metrics.tags.application: ${spring.application.name}


logging:
  config: classpath:log4j2-plain.xml


bot:
  base-url: http://localhost:8090


github:
  base-url: https://api.github.com


stackoverflow:
  base-url: https://api.stackexchange.com


springdoc:
  swagger-ui:
    path: /swagger-ui
