app:
  telegram-bot-token: ${TELEGRAM_TOKEN}
  telegram-bot-name: LinkUpdateTrackerBot

  kafka:
    topic:
      name: "notifications"


spring:
  application:
    name: bot

  jackson:
    time-zone: UTC

  kafka:
    bootstrap-servers: localhost:29091
    consumer:
      group-id: consumer-group-1
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "edu.java.dto.request"
    listener:
      concurrency: 1


server:
  port: 8090

scrapper:
  base-url: http://localhost:8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
