app:
  telegram-bot-token: ${TELEGRAM_TOKEN}
  telegram-bot-name: LinkUpdateTrackerBot

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

scrapper:
  base-url: http://localhost:8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
