/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables;

import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.tables.records.LinksChatsRecord;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class LinksChats extends TableImpl<LinksChatsRecord> {

    /**
     * The reference instance of <code>LINKS_CHATS</code>
     */
    public static final LinksChats LINKS_CHATS = new LinksChats();
    private static final long serialVersionUID = 1L;
    /**
     * The column <code>LINKS_CHATS.CHAT_ID</code>.
     */
    public final TableField<LinksChatsRecord, Long> CHAT_ID =
        createField(DSL.name("chat_id"), SQLDataType.BIGINT.nullable(false), this, "");
    /**
     * The column <code>LINKS_CHATS.LINK_ID</code>.
     */
    public final TableField<LinksChatsRecord, Long> LINK_ID =
        createField(DSL.name("link_id"), SQLDataType.BIGINT.nullable(false), this, "");
    private transient Chats _chats;
    private transient Links _links;

    private LinksChats(Name alias, Table<LinksChatsRecord> aliased) {
        this(alias, aliased, null);
    }

    private LinksChats(Name alias, Table<LinksChatsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LINKS_CHATS</code> table reference
     */
    public LinksChats(String alias) {
        this(DSL.name(alias), LINKS_CHATS);
    }

    /**
     * Create an aliased <code>LINKS_CHATS</code> table reference
     */
    public LinksChats(Name alias) {
        this(alias, LINKS_CHATS);
    }

    /**
     * Create a <code>LINKS_CHATS</code> table reference
     */
    public LinksChats() {
        this(DSL.name("links_chats"), null);
    }

    public <O extends Record> LinksChats(Table<O> child, ForeignKey<O, LinksChatsRecord> key) {
        super(child, key, LINKS_CHATS);
    }

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<LinksChatsRecord> getRecordType() {
        return LinksChatsRecord.class;
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<LinksChatsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_453;
    }

    @Override
    @NotNull
    public List<ForeignKey<LinksChatsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_453B, Keys.CONSTRAINT_453BC);
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.CHATS</code> table.
     */
    public Chats chats() {
        if (_chats == null) {
            _chats = new Chats(this, Keys.CONSTRAINT_453B);
        }

        return _chats;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINKS</code> table.
     */
    public Links links() {
        if (_links == null) {
            _links = new Links(this, Keys.CONSTRAINT_453BC);
        }

        return _links;
    }

    @Override
    @NotNull
    public LinksChats as(String alias) {
        return new LinksChats(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public LinksChats as(Name alias) {
        return new LinksChats(alias, this);
    }

    @Override
    @NotNull
    public LinksChats as(Table<?> alias) {
        return new LinksChats(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinksChats rename(String name) {
        return new LinksChats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinksChats rename(Name name) {
        return new LinksChats(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinksChats rename(Table<?> name) {
        return new LinksChats(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
