/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq;

import edu.java.domain.jooq.tables.Chats;
import edu.java.domain.jooq.tables.Links;
import edu.java.domain.jooq.tables.LinksChats;
import edu.java.domain.jooq.tables.records.ChatsRecord;
import edu.java.domain.jooq.tables.records.LinksChatsRecord;
import edu.java.domain.jooq.tables.records.LinksRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatsRecord> CONSTRAINT_3 =
        Internal.createUniqueKey(Chats.CHATS, DSL.name("CONSTRAINT_3"), new TableField[] {Chats.CHATS.CHAT_ID}, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_4 =
        Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_4"), new TableField[] {Links.LINKS.LINK_ID}, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_45 =
        Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_45"), new TableField[] {Links.LINKS.URL}, true);
    public static final UniqueKey<LinksChatsRecord> CONSTRAINT_453 = Internal.createUniqueKey(LinksChats.LINKS_CHATS,
        DSL.name("CONSTRAINT_453"),
        new TableField[] {LinksChats.LINKS_CHATS.CHAT_ID, LinksChats.LINKS_CHATS.LINK_ID},
        true
    );

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LinksChatsRecord, ChatsRecord> CONSTRAINT_453B =
        Internal.createForeignKey(LinksChats.LINKS_CHATS,
            DSL.name("CONSTRAINT_453B"),
            new TableField[] {LinksChats.LINKS_CHATS.CHAT_ID},
            Keys.CONSTRAINT_3,
            new TableField[] {Chats.CHATS.CHAT_ID},
            true
        );
    public static final ForeignKey<LinksChatsRecord, LinksRecord> CONSTRAINT_453BC = Internal.createForeignKey(
        LinksChats.LINKS_CHATS,
        DSL.name("CONSTRAINT_453BC"),
        new TableField[] {LinksChats.LINKS_CHATS.LINK_ID},
        Keys.CONSTRAINT_4,
        new TableField[] {Links.LINKS.LINK_ID},
        true
    );
}
